# -*- coding: utf-8 -*-
"""numpy_assignment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dvrOMR-Wvd5iVS5wXUENTCr8qfyowMrU
"""

import pandas as pd
import numpy as np
df = pd.read_csv('/content/StudentsPerformance.csv')
df

#2. Display the first 5 rows of the dataset.
df.head()

#3. Display the last 5 rows of the dataset.
df.tail()

#4. Check the shape, size, and ndim attributes of the DataFrame.
print(df.shape)
print(df.size)
print(df.ndim)

#5. Display the column names.
print(df.columns)

df.dtypes

df.isna().sum()

#8
df['math score'],['reading score']

#09
df['gender'].value_counts()

#10
print(df['lunch'].unique())

#part 02
#Q.1 1. Find and display the records of students who scored more than 80 in
# math score.
a=df['math score']>80
a

#2. Find and display the records of students
#who scored less than 50 in writing score.
a=df['writing score']<50
a

#3. Filter and display the students who completed the test preparation course.
df[df['test preparation course']=='completed']

# 4. Find and display the records of female students with a reading score greater
# than 70.
df[(df['gender'] == 'female') & (df['reading score'] > 70)]

#05
df[df['lunch'] == 'free/reduced']

# part 03
# 01 Find the average of the math score.
print(df['math score'].mean())

# 2. Find the maximum and minimum values in the reading score column.
print(df['reading score'].min())
print(df['reading score'].max())

#3. Count the number of students grouped by race/ethnicity.
df.groupby('race/ethnicity').count()

#4 Find the average writing score grouped by gender.
df.groupby('gender')['writing score'].mean()

#5. Sort the students by math score in descending order and display the top 10.
df['math score'].sort_values(ascending=False).head(10)

# Part 4: Beginner Friendly Tasks
# 1. Create a new column named total_score, which is the sum of math score,
# reading score, and writing score.
df['total_score'] = df['math score'] + df['reading score'] + df['writing score']

#2. Create a new column named average_score (total score divided by 3).
df['average_score'] = df['total_score'] / 3
df

# 3. Add a column named result. A student passes if their average_score is 60 or
# above; otherwise, they fail. (Hint: Use a conditional function or lambda expression).
df['result'] = df['average_score'].apply(lambda x: 'Pass' if x >= 60 else 'Fail')
df

#4. Find the top 5 students based on their total_score.
df.sort_values(by='total_score', ascending=True).head(5)

#5. Find the bottom 5 students based on their math score.
df.sort_values(by='math score', ascending=True).head(5)


#df('math score').sort_value(acending=False).head(5)